### ISSUE TITLE
[Question] Speed up reading only what I need

### ISSUE THREAD

**Issue by StefanoTesla** [openspout/openspout#100]
I was testing this library to open some large files, and it take 3sec.

I don't know how xlsx file are structured and if is necessary, but if I open a file and I do a

```
        foreach ($reader->getSheetIterator() as $sheet) {
            dd($sheet);
        }
```

All the page is already readed under the hood:

![screen](https://user-images.githubusercontent.com/92517402/196137354-48218123-8661-43e2-86a7-ffe0dff6484e.jpg)

Is there a way to open and read only the necessary page/rows without caching everything?

**Comment by Slamdunk** [comment]
> Is there a way to open and read only the necessary page/rows without caching everything?

Good question, the answer is that I don't know.

What I know is that this library aims to keep memory consumption as low as possible, see https://github.com/openspout/openspout/blob/4.x/benchmarks/XlsxReaderSharedBench.php

Any PR is very welcome

**Comment by StefanoTesla** [comment]
Yes, but not every time, looking on the box\spout there's a "caching strategy" streaming the data coming from the xml reader """"""""nothing of special""""""""
but he read all the xlsx file
, this because in the sharedStrings.xml file there'are all the strings of the spreadsheet independently from the page, ex:


Spreadsheet with two pages in workbook.xml will be:

```
<sheets>
    <sheet name="Sheet1" sheetId="1" r:id="rId1"/>
    <sheet name="Foglio1" sheetId="2" r:id="rId2"/>
</sheets>
```
But the sharedString.xml will always be:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="2" uniqueCount="2">
<si>
<t>a</t>
</si>
<si>
<t>b</t>
</si>
</sst>
```

I need to understand how he understand when the page finish in the  sharedString.xml...

**Comment by StefanoTesla** [comment]
Update:

in the xl\worksheets folder there's one file for each sheet.

Inside of it you can find the sheet structure like this:


sheet1:

```
     <sheetData>
        <row r="1" spans="1:1" x14ac:dyDescent="0.25">
            <c r="A1" t="s"><v>0</v></c>
        </row>
    </sheetData>
```

and sheet2:

```
    <sheetData>
        <row r="1" spans="1:2" x14ac:dyDescent="0.25">
            <c r="A1" t="s"><v>1</v></c>
            <c r="B1" t="s"><v>7</v></c>
        </row>
        <row r="2" spans="1:2" x14ac:dyDescent="0.25">
            <c r="A2" t="s"><v>2</v></c>
        </row>
        <row r="3" spans="1:2" x14ac:dyDescent="0.25">
            <c r="A3" t="s"><v>3</v></c>
        </row>
        <row r="4" spans="1:2" x14ac:dyDescent="0.25">
            <c r="A4" t="s"><v>4</v></c>
        </row>
        <row r="5" spans="1:2" x14ac:dyDescent="0.25">
            <c r="A5" t="s"><v>5</v></c>
        </row>
        <row r="6" spans="1:2" x14ac:dyDescent="0.25">
            <c r="A6" t="s"><v>6</v></c>
        </row>
    </sheetData>
```

All the numbers inside the <v> tags call the string number inside the sharedStrings.xml

```
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="8" uniqueCount="8">
    <si><t>a</t></si>   //0
    <si><t>b</t></si>   //1
    <si><t>c</t></si>   //2
    <si><t>d</t></si>   //3
    <si><t>e</t></si>   //4
    <si><t>f</t></si>   //5
    <si><t>g</t></si>   //6
    <si><t>h</t></si>   //7
</sst>
```

I think is for this reason that the majority parts of the php-excel libraryes don't read the file using an asyncrounus way, cause you need to read all the sharedStrings for associate the row value to the cells you are reading...


Ok, I lost some hours but I learn something :D
