### ISSUE TITLE
Excel complains about corrupted XLSX files?

### ISSUE THREAD

**Issue by spackmat** [openspout/openspout#102]
Hi, this issue is a sort of FAQ or placeholder for others experiencing Excel complaining about corrupted XLSX files and are looking for that problem here.

This is not related to the problem on windows that was fixed with release 4.7.0 (see #87, #85, #90 and #97).

I implemented a simple XLSX-export (or ODS) and Excel kept complaining even with the basic examples from the docs. 7-zip and LibreOffice didn't complain and could open the generated files whatsoever. After some lost hair it turned out that I simply forgot an `exit;` statement after `$writer->close();` so that the zipped file ended with html code from the page containing the export.

A simple example would be:

````php
<?php
if (isset($_GET['export'])) {
    $writer = new OpenSpout\Writer\XLSX\Writer();
    $writer->openToBrowser('example.xlsx');
    
    $writer->addRow(OpenSpout\Common\Entity\Row::fromValues([
        'foo',
        'bar',
    ]));
    
    // this sends the file to the browser, but does not terminate the script 
    $writer->close();
    
    // so don't forget this, otherwise the html below is attached to the exported file
    // or prevent other output after sending the file in any other way you like
    exit; 
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>export example</title>
</head>
<body>
    <a href="?export">XLSX export</a>
</body>
</html>
````

P.S. Other libs, that send their created files directly to the browser, just do that exit afterwards on their own, terminating the whole script. I don't want to suggest that behavior for openspout, as from my point of view leaving that decision to the consuming party is the correct and humble way. But maybe the code examples in the docs could use that `exit` when `openToBrowser()` is used so that oblivious devs don't forget it.

**Comment by Slamdunk** [comment]
> But maybe the code examples in the docs could use that `exit` when `openToBrowser()` is used so that oblivious devs don't forget it.

Can you open a PR please?

**Comment by spackmat** [comment]
@Slamdunk OK, PR is in #103
