### ISSUE TITLE
How to merge cell based on sheet?

### ISSUE THREAD

**Issue by afiqiqmal** [openspout/openspout#104]
The options only take effect on first sheet only. When i move into the loop, the excel became corrupted. How to achieve this?

```php
$writer = WriterFactory::createFromFile($path);
$writer->getOptions()->mergeCells(0, 1, 3, 1);
$writer->openToFile($path);

for loop {
   // add row
   // $writer->addNewSheetAndMakeItCurrent();
}

$writer->close();
```

**Comment by Slamdunk** [comment]
I'm not sure what the issue is, but have you tried playing around with the 5th parameter of the `mergeCells` method?

**Comment by afiqiqmal** [comment]
Ah.. there is 5th params.. Need to drill down the code instead of documentation 😅
