### ISSUE TITLE
Add reader factory

### ISSUE THREAD

**Issue by atomatis** [openspout/openspout#106]
Hi,

(sorry by advance for my bad english)
I use often a custom reader factory with spout, for simple read case, like import, view,...

ex:`ReaderFactory::createReader(string $file): ReaderInterface`

The factory try guessing $file type with extention and mime type. 

I am willing to post a PR if people are interested.

**Comment by Slamdunk** [comment]
That's what https://github.com/openspout/openspout/blob/4.x/src/Reader/Common/Creator/ReaderFactory.php does, isn't it?

**Comment by atomatis** [comment]
I miss this, sorry!

I couldn't find the factory in the documentation, so I assumed it didn't exist -_-
Maybe add a little section for information.

**Comment by Slamdunk** [comment]
> I miss this, sorry!
> 
> I couldn't find the factory in the documentation, so I assumed it didn't exist -_- Maybe add a little section for information.

A PR for the documentation would be very welcome :)

**Comment by atomatis** [comment]
With pleasure :)

I will send this during the day.

**Comment by atomatis** [comment]
#107
