### ISSUE TITLE
Any reason for $row->toArray() to be @internal ?

### ISSUE THREAD

**Issue by FluffyDiscord** [openspout/openspout#118]
Any reason to have `->toArray()` as internal function ?

File in question `vendor/openspout/openspout/src/Common/Entity/Row.php`
line 137
```php
    /**
     * @internal
     *
     * @return list<null|bool|DateInterval|DateTimeInterface|float|int|string> The row values, as array
     */
    public function toArray(): array
    {
        return array_map(static function (Cell $cell): null|bool|string|int|float|DateTimeInterface|DateInterval {
            return $cell->getValue();
        }, $this->cells);
    }
```

**Comment by Slamdunk** [comment]
Because it's only used in tests right now

**Comment by FluffyDiscord** [comment]
I think its reasonable helper function to be used anywhere, even outside the tests. Would it be possible to remove the `@internal` annotation ?

**Comment by Slamdunk** [comment]
Yes: use an array with all possible values, and assert that:

```php
self::assertEquals($arrayWithValues, Row::fromValues($arrayWithValues)->toArray());
```

**Comment by Slamdunk** [comment]
I mean, propose a Pull-Request with that test, alongside the removal of the `@internal` annotation
