### ISSUE TITLE
Reading and writing cell-comments

### ISSUE THREAD

**Issue by jverelst** [openspout/openspout#122]
Hi,

First of all, thanks for starting this fork and the fact that the code is still actively maintained! My question: are there any plans to implement cell comments (reading and writing) for XLSX files? I am working on a project that has heavy dependencies on PHPOffice and I am rewriting it to use spout for the obvious benefits of speed and memory usage. 

I did however notice that cell-comments are not supported, is that something that might be implemented in the future? I can also try to implement it myself and create a PR, but maybe somebody could give me some pointers on what the cleanest way would be to implement this?

**Comment by Slamdunk** [comment]
Hi, my work here is to provide low level maintenance, I have no idea how comments are implemented in XLSX but I'll be very happy to accept PRs for them and to guide you to have the build green

**Comment by jverelst** [comment]
@Slamdunk I've created a PR #123, so looking forward to your feedback

**Comment by jverelst** [comment]
Since #123 has been merged, closing this issue.
