### ISSUE TITLE
Inconsistent boolean values when writing to CSV

### ISSUE THREAD

**Issue by devfrey** [openspout/openspout#133]
When a `BooleanCell` containing `false` is written to a CSV file the resulting value will be empty (`''` to be exact), whereas a `BooleanCell` containing `true` will result in `'1'`. This is because all [cell values are cast to strings here](https://github.com/openspout/openspout/blob/4.x/src/Writer/CSV/Writer.php#L53) and PHP casts `false` to an empty string ([reference](https://www.php.net/manual/en/language.types.string.php#language.types.string.casting)). I would expect `false` to result in `'0'` in the CSV.

Now this could be solved in consumer code by explicitly casting booleans to integers, but ideally we'd fix this in the CSV writer. I couldn't find any tests covering this behaviour, so I'm unsure whether it's intentional or accidental.

What are your thoughts? Could this be a bug fix?

**Comment by Slamdunk** [comment]
> What are your thoughts? Could this be a bug fix?

Sure, give it a try with a PR and a regression test :+1:
