### ISSUE TITLE
Streaming XLSX

### ISSUE THREAD

**Issue by mgsmus** [openspout/openspout#135]
Hello. First of all thanks for the fantastic package! 

I'm having a problem with streaming. Something unexpected is happening with xlsx while I can successfully stream csv. When I try to stream xlsx on the server, instead of starting to download the file byte by byte, it just waits and gives me the whole file in one go. That's why I'm having timeout issues. I'm not sure if this is expected or if there is a problem.

This works as expected:
```php
$writer = new \OpenSpout\Writer\CSV\Writer();

$response = new StreamedResponse(function () use ($writer) {
    $writer->openToBrowser('data.csv');
    
    for ($i=0; $i < 1000000; $i++) {
        $cells = [
            Cell::fromValue(uniqid()),
            Cell::fromValue(uniqid()),
            Cell::fromValue(uniqid()),
        ];

        $row = new Row($cells);

        $writer->addRow($row);
    }

    $writer->close();
});

$response->headers->set('Content-Type', 'text/csv');

return $response;
```
But this doesn't work like csv:
```php
$writer = new \OpenSpout\Writer\XLSX\Writer();

$response = new StreamedResponse(function () use ($writer) {
    $writer->openToBrowser('data.xlsx');

    for ($i=0; $i < 1000000; $i++) {
        $cells = [
            Cell::fromValue(uniqid()),
            Cell::fromValue(uniqid()),
            Cell::fromValue(uniqid()),
        ];

        $row = new Row($cells);

        $writer->addRow($row);
    }
    $writer->close();
});

$response->headers->set('Content-Type', 'application/vnd.ms-excel');

return $response;
```

Am I missing something?

Thanks.

**Comment by Slamdunk** [comment]
> instead of starting to download the file byte by byte, it just waits and gives me the whole file in one go.

That's expected.
An XLSX is a ZIP of many XML files.
You need the entire directory structure before starting to ZIP it.
Then you ZIP it.
Only then you can send it.

**Comment by mgsmus** [comment]
Thanks @Slamdunk, makes sense.

**Comment by lekoala** [comment]
I know this issue is closed but i think it should be possible to stream xlsx when using this

https://maennchen.dev/ZipStream-PHP/guide/index.html

but i haven't tried :-)
