### ISSUE TITLE
How to create Excel file with autofilter?

### ISSUE THREAD

**Issue by LPRKR** [openspout/openspout#138]
Hi! I can't find a way to mark the first row as the autofilter row.
Does it mean it's not possible with this library?

**Comment by Slamdunk** [comment]
Yes it is, although it hasn't been documented yet.

Have a look at these tests: https://github.com/openspout/openspout/pull/78/files#diff-c6264e46c5a27a867f62ef8f69fb66d44fc8762b1b994b93f17536aaff0b5e21

**Comment by LPRKR** [comment]
It works, thank you! :)
