### ISSUE TITLE
Error "Undefined array key 1" when reading some xlsx

### ISSUE THREAD

**Issue by zxl409774878** [openspout/openspout#141]
https://github.com/openspout/openspout/blob/e01cab951c04ef184c567a880290997e94386f94/src/Reader/XLSX/RowIterator.php#L299-L303
Some xlsx files can be read normally by Office Excel, but openspout will return an empty string '' here $spans, causing it to pass the if judgment and then report an error “Undefined array key 1”.

https://github.com/box/spout/blob/84596668410bea89d21aa9867b91e1550e359329/src/Spout/Reader/XLSX/RowIterator.php#L258-L262

If the judgment method of the original version of Spout is modified, the file can be read normally.

**Comment by Slamdunk** [comment]
Nice catch! Can you propose a fix on a dedicated pull-request please?
