### ISSUE TITLE
Dates become integers when saving xlsx

### ISSUE THREAD

**Issue by hkirsman** [openspout/openspout#149]
Dates become integers like 44949 and I can't figure out why.

I'm reading in one spreadsheet, then writing another one.

In the reader it seems ok:
![image](https://user-images.githubusercontent.com/492375/236685234-07a49327-cef6-4ba7-ac96-b4bf265878c5.png)

I then use the array and write back to new row:

    $rowFormValues = Row::fromValues($new_row);
    $writer->addRow($rowFormValues);

I've also tried to use the code from example to write date but the same happens:

  $row[2] = new \DateTimeImmutable('now');

I've tested this is in LibreOffice and Office 2013

**Comment by hkirsman** [comment]
For now I'll change the date object back to string:

          foreach ($row as $key => $value) {
            if ($value instanceof \DateTimeImmutable) {
              $row[$key] = $value->format('d/m/Y');
            }
          }

**Comment by Slamdunk** [comment]
Can you write a small self-contained code sample with the expected behavior?

**Comment by hkirsman** [comment]
Sure, this would be the example code:

```php
namespace OpenSpoutDateIssue;

require_once __DIR__ . '/../vendor/autoload.php';

use OpenSpout\Reader\XLSX\Reader as XLSXReader;
use OpenSpout\Writer\XLSX\Writer as XLSXWriter;
use OpenSpout\Common\Entity\Row;

// Create "OpenSpout" reader.
$reader = new XLSXReader();
$reader->open('source.xlsx');

// Create "OpenSpout" writer.
$writer = new XLSXWriter();
$writer->openToFile('out.xlsx');

// Read in the source file and write it out to the destination file.
// Add also new date column to the end of each row that has the date as a
// string.
foreach ($reader->getSheetIterator() as $sheet) {
  foreach ($sheet->getRowIterator() as $row_object) {
    $row = $row_object->toArray();

    foreach ($row as $key => $value) {
      if ($value instanceof \DateTimeImmutable) {
        $row[$key + 1] = $value->format('d.m.Y');;
      }
    }

    $rowFormValues = Row::fromValues($row);
    $writer->addRow($rowFormValues);
  }
  $reader->close();
  $writer->close();
}

```

This is the source file with some date cells:
[source.xlsx](https://github.com/openspout/openspout/files/11419096/source.xlsx)

This is what I get in out.xlsx - the first column dates are integeres:
![image](https://user-images.githubusercontent.com/492375/236768767-07b9a3aa-03c4-480a-b2be-916ea207eb61.png)

I'm using version OpenSpouot 4.13.1 and PHP 8.2

**Comment by Slamdunk** [comment]
Dates in XSLX are always plain numbers, you need to format them in a specific way in order to render them as a Date:

```php
$writer = new XLSXWriter();
$writer->openToFile('out2.xlsx');

$date = new \DateTimeImmutable('2023-01-23');

$writer->addRow(new Row([
    Cell::fromValue($date),
    Cell::fromValue($date, (new Style())->setFormat('yyyy-mm-dd')),
]));

$writer->close();
```

![image](https://user-images.githubusercontent.com/152236/236776259-66ffe303-e9be-45b3-9d2c-e98077709d4c.png)

**Comment by hkirsman** [comment]
Ok, so when reading one file and writing another, I should not use
$row = $row_object->toArray();
but rather
$cells_array = $row_object->getCells();

Then if the cell is of type DateTimeCell, overwrite the cell with the original value + style.

```php
foreach ($reader->getSheetIterator() as $sheet) {
  foreach ($sheet->getRowIterator() as $row_object) {
    $cells_array = $row_object->getCells();
    foreach ($cells_array as $key => $value) {
      if ($value instanceof DateTimeCell) {
        $cells_array[$key] = Cell::fromValue($value->getValue(), (new Style())->setFormat('yyyy-mm-dd'));
      }
    }

    $new_row = new Row($cells_array);
    $writer->addRow($new_row);
  }
  $reader->close();
  $writer->close();
}

```
