### ISSUE TITLE
Slow FileBasedStrategy on Windows

### ISSUE THREAD

**Issue by adawolfa** [openspout/openspout#155]
[This condition](https://github.com/openspout/openspout/blob/8f0e9576bdccd6f512fa614216fd58db71337992/src/Reader/XLSX/Manager/SharedStringsCaching/FileBasedStrategy.php#L124) seems to be always passing on Windows, because `$inMemoryTempFilePath` is normalized using `realpath()` while the `$tempFilePath` is not.

| variable | value |
|---|---|
| `$this->inMemoryTempFilePath` | `C:\...\Temp\sharedstrings64676f752d764\sharedstrings0` |
| `$tempFilePath` | `C:\...\Temp\sharedstrings64676f752d764/sharedstrings0` |

Notice the incorrect directory separator (a slash rather than a backslash) ahead of the base name part.

This causes the temporary file to be re-loaded on every single shared string access, making it very slow, especially on XLSX's with a lot of shared strings.

**Comment by Slamdunk** [comment]
Thank you for noticing it: can you try the fix locally, and if works propose it in a Pull Request please?
