### ISSUE TITLE
How to get raw formula from cell?

### ISSUE THREAD

**Issue by Kadigan** [openspout/openspout#168]
Hey there.

Thank you for making this. It's helped me out a number of times so far.

**How do I get the raw value/formula of a cell?** I'm using references in my document (e.g. `='Sheet name'!$Row$Cell`), but when I call `->getValue()` I get the dereferenced value from the sheet. Is there a way to get the raw formula?

**Comment by Slamdunk** [comment]
From version `v4.16`, `FormulaCell::getValue` gives the formula, while `FormulaCell::getComputedValue` gives the computed value, if available.

**Comment by Kadigan** [comment]
And how would I go about getting it to produce them as `FormulaCell`s? I'm getting `StringCell`s, and Google is being supremely unhelpful.

**Comment by Slamdunk** [comment]
Since `v4.16` it is automatic: just update the library, and `getValue()` will now return the formula
