### ISSUE TITLE
Excel support for DateInterval

### ISSUE THREAD

**Issue by uncaught** [openspout/openspout#176]
The `OpenSpout\Writer\XLSX\Manager\WorksheetManager::getCellXML` method doesn't handle the `DateIntervalCell`, leaving the XML with broken unclosed tags:

![image](https://github.com/openspout/openspout/assets/10322643/6332a03f-f626-4fab-847a-d962b5efe2b5)

**Comment by Slamdunk** [comment]
Can you reproduce the bug in a test?

**Comment by uncaught** [comment]
Yes, see https://github.com/hcomde/octaved-flow-openspout/commit/ecebd40785fa52ae7569242c4a8c2d68a943d02c#diff-c6264e46c5a27a867f62ef8f69fb66d44fc8762b1b994b93f17536aaff0b5e21

If you run this without the patch to the WorksheetManager, the `loadXML` will return `false` and fail the test.

**Comment by Slamdunk** [comment]
Cool can you propose a PR here with the fix please?

**Comment by uncaught** [comment]
Sure, #177 is open :)
