### ISSUE TITLE
Row::fromValues return array of cells which cannot be written by CSVWriter

### ISSUE THREAD

**Issue by blazekv** [openspout/openspout#199]
Maybe I did not get correctly API and how to use it. But there is strange behavior when I have array of different objects and use Row::fromValues.

I have array like this one:
```
array(8) {
  ["firstName"]=>
  string(10) "John"
  ["lastName"]=>
  string(7) "Doe"
  ["created"]=>
  object(DateTime)#2068 (3) {
    ["date"]=>
    string(26) "2023-11-16 09:21:25.000000"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(3) "UTC"
  }
  ["notes"]=>
  NULL
 }
```

If I use **OpenSpout\Common\Entity\Row::fromValues** I got array of 4 cells and one of them is **DateTimeCell**. When I tried to write these cells by OpenSpout\Writer\XLSX\Writer everything is OK. But when I try to write these cells by OpenSpout\Writer\CSV\Writer it will throw exception because addRowToWriter [does not support DateTimeCell](https://github.com/openspout/openspout/blob/c0ece0d8c5d493fba6913c5c73d70887da249127/src/Writer/CSV/Writer.php#L52C9-L58C30).

Is it intended? If so why is only one method for converting data to cells instead of several different method or one which will return cells according to format (CSV, XLSX).

**Comment by Slamdunk** [comment]
> Is it intended?

No it isn't, to put it simply no one ever tried to write a `DateTimeCell` into a CSV :smile_cat: 

Any PR to fix this is welcome

**Comment by blazekv** [comment]
OK, thanks. I will look at it and try to fix it.
