### ISSUE TITLE
Supporting 3 PHP versions

### ISSUE THREAD

**Issue by yurikuzn** [openspout/openspout#202]
We've been using Openspout as an optional alternative for PHPSpreadsheet in our open source CRM for a while and it worked great.

We run into a problem with PHP version support. We have a policy of supporting all 3 minor PHP versions (8.0 - 8.2 currently, and 8.1 - 8.3 soon as 8.0 will be EOL). Previously, we used an Openspout version that supported 8.0 - 8.2. I see that the new release supports only 8.2 - 8.3. As our product is shipped ready to use w/o the need to run *composer install*, we currently cannot switch to PHP 8.3 w/o resolving this dependency issue.

Hence, I wanted to ask, wouldn't you consider to support 3 PHP versions rather than 2?

Thank you for your work.

**Comment by Slamdunk** [comment]
> Wouldn't you consider to support 3 PHP versions rather than 2?

Sure! That would be € 300 to cover the 8.1 - 8.3 range for the upcoming 12 months.

Ping me if you are interested :+1:

**Comment by yurikuzn** [comment]
Fine. Would it be OK if we pay through the GitHub sponsorship?

**Comment by Slamdunk** [comment]
Ok: a one-time € 300 sponsorship will grant support to `openspout/openspout` for PHP 8.1, 8.2 & 8.3 untill `2024-11-30` :+1:

**Comment by yurikuzn** [comment]
Done, from https://github.com/espocrm account 🎉, GitHub offered only $, I converted to € with Google.

**Comment by Slamdunk** [comment]
Thank you for your support, PHP 8.1 support re-added in [`v4.22.0`](https://github.com/openspout/openspout/releases/tag/v4.22.0) :beers:
