### ISSUE TITLE
upgrading from v3 to v4, question with the new code

### ISSUE THREAD

**Issue by rebbieboi** [openspout/openspout#211]
the v3 code is below:

use OpenSpout\Reader\Common\Creator\ReaderEntityFactory;
use OpenSpout\Writer\Common\Creator\WriterEntityFactory;

this will work for either csv or xlsx.

The new code is below:

use OpenSpout\Reader\XLSX\Reader;
use OpenSpout\Writer\XLSX\Writer;

OR

use OpenSpout\Reader\CSV\Reader;
use OpenSpout\Reader\CSV\Writer;

Does this mean I have to include both options if I will deal with either CSV or XLSX or will either just detect what I'm using and work for it?

**Comment by rebbieboi** [comment]
I implemented it as

use OpenSpout\Reader\XLSX\Options as xlsx_option;
use OpenSpout\Reader\XLSX\Reader as xlsx_reader;
use OpenSpout\Writer\XLSX\Writer as xlsx_writer;
use OpenSpout\Reader\CSV\Options as csv_option;
use OpenSpout\Reader\CSV\Reader as csv_reader;
use OpenSpout\Writer\CSV\Writer as csv_writer;

**Comment by zeliangong** [comment]
WriterEntityFactory is not a valid class in v4, the above solution is correct
