### ISSUE TITLE
Set column width in v3 

### ISSUE THREAD

**Issue by mtami** [openspout/openspout#213]
Hi community,
I have a legacy old system that run PHP 7.4 .
I cannot upgrade PHP to the latest supported versions since this requires much effort.
I came recently to use openspout, I can see that openspout V4 supports setColumnWidth.
However, is there any way to do this in openspout v3.7.4 ?

**Comment by Slamdunk** [comment]
Yes, with much effort: I can give you a quote if you need :+1:

**Comment by mtami** [comment]
Hi @Slamdunk appreciate your commitment to this awesome library.
If you could guide me to where I could start or look that would be great!

**Comment by Slamdunk** [comment]
Look in the PR that introduced it, and try to fit it in `v3`: https://github.com/openspout/openspout/pull/140

Beware though that I won't merge any PR related to `v3`, you'll have to keep your patch for yourself, using something like https://github.com/cweagans/composer-patches
