### ISSUE TITLE
Right To Left Support

### ISSUE THREAD

**Issue by AshrafBasry** [openspout/openspout#221]
How to make sheet right to left?

**Comment by Slamdunk** [comment]
I have no idea: if you find a solution, please share it here, or better, propose a PR 💪

**Comment by AshrafBasry** [comment]
Sorry, It was there all the time but not documented well
[SheetView](https://github.com/openspout/openspout/blob/87f466ce3890667f57ab40ab255f59af1dd8348c/src/Writer/XLSX/Entity/SheetView.php#L73)
