### ISSUE TITLE
Writing XLSX with Cell::fromValue and style produces invalid XLSX files when using special characters

### ISSUE THREAD

**Issue by rikvdh** [openspout/openspout#261]
I'm facing an issue with the XLSX writer where the value provided in Cell values and styles are raw injected into the XML-file and not escaped.

Characters like: `"`, `<` and `>` are producing xlsx files which crap out in Excel.

With some specific formatting rules with currency symbols like: `"€"* #,##0.00_-` is invalid (whilst valid in phpspreadsheet). I think the xlsx writer needs something like: `strtr($value, ['>' => '&gt;', '<' => '&lt;', '"' => '&quot;'])`.

**Comment by Slamdunk** [comment]
[`htmlspecialchars`](https://www.php.net/manual/en/function.htmlspecialchars.php) can also be used.

Can you open a PR with the fix please?

**Comment by rikvdh** [comment]
I'll work on this later today or tomorrow.. I'll also make some tests and verify that Excel is opening the produced files correctly.
