### ISSUE TITLE
Unable to extend cell classes (NumericCell, StringCell etc)

### ISSUE THREAD

**Issue by cztc101** [openspout/openspout#276]
I'm working on a project that requires me to extend the NumericCell class but I'm unable to do so because the class has been coded as a final class. Please can this be changed as I'm now unable to write in the necessary functionality which is a problem. Considering that the package is open source I think it makes sense for developers to be able to extend the classes. This also has been marked as a problem by another developer: see https://github.com/openspout/openspout/issues/255

Please can you consider allowing the classes to be extended. Many thanks!

**Comment by Slamdunk** [comment]
Replied in https://github.com/openspout/openspout/issues/255#issuecomment-2415977630
