### ISSUE TITLE
v4.28.0 broken public api

### ISSUE THREAD

**Issue by lekoala** [openspout/openspout#286]
I don't know if its intentional, but https://github.com/openspout/openspout/releases/tag/v4.28.0 removed public setCreator method from the XLSX Writer as part of https://github.com/openspout/openspout/pull/285/files and it seems very odd that this is done on a minor release ?
Or I've missed something in the recent updates

i would keep the setCreator method and simply make it update the underlying properties object (it's readonly, so it's a bit tricky if you keep it that way)

**Comment by Slamdunk** [comment]
You are right: would you please send a PR to fix it?

**Comment by lekoala** [comment]
i think this should do the job
https://github.com/openspout/openspout/pull/287/files

i don't see real benefits in having properties as readonly. if we want to keep them readonly, then setCreator needs to read the properties, create a new ones et replace them but that seem a lot of work for no good reason
