### ISSUE TITLE
Add setCellVerticalAlignment() & allow setShouldWrapText() to be explicitly set as false

### ISSUE THREAD

**Issue by jonnott** [openspout/openspout#62]
Does this fork already do the things in this PR, or is it worth re-targeting the PR at this fork instead? Getting frustrated at the lack of any signs of life from box/spout :)

https://github.com/box/spout/pull/869

**Comment by Slamdunk** [comment]
I plan to implement it this week, stay tuned

**Comment by jonnott** [comment]
Next thing I'm struggling with relating to formatting rows is: how can I set the height for a specific row? In XLSXWriter, I can use `height` in row options.

I'm using `$writer->addRow(Row::fromValues($row, $style));` to add a row, but how can I explicitly set the height?

@Slamdunk any ideas?

**Comment by Slamdunk** [comment]
> Next thing I'm struggling with relating to formatting rows is: how can I set the height for a specific row?

Currently that's not possible, but PR are welcome

**Comment by jonnott** [comment]
> > Next thing I'm struggling with relating to formatting rows is: how can I set the height for a specific row?
> 
> Currently that's not possible, but PR are welcome

What was the deal with the setHeight/getHeight methods which were recently added but then removed? Would they be a starting point if I was to make a PR?

**Comment by Slamdunk** [comment]
> What was the deal with the setHeight/getHeight methods which were recently added but then removed?

What code are you referring to?

**Comment by jonnott** [comment]
> > What was the deal with the setHeight/getHeight methods which were recently added but then removed?
> 
> What code are you referring to?

This code:

https://github.com/openspout/openspout/commit/f8b7a6b28ded8005fb43c2772391abafc437f816

**Comment by Slamdunk** [comment]
Oh, sure :+1:

**Comment by jonnott** [comment]
@Slamdunk  I'm utterly stuck with this one a would appreciate a pointer in the right direction. I've started by reverting the changes in the above commit so I have a height property on the row, and a getter/setter for a height. But I can't figure out where setting the height on a row would actually go into the XML output, and/or if this could be set as an attribute of a row style? 

I'm been looking at the code of XLSXWriter to compare, but I still can't figure things out from there. It seems like XLSXWriter uses 12.1 as the default row height unless something else if specified, see https://github.com/mk-j/PHP_XLSXWriter/blob/4da41e4f5df8333d17028aabf2a74e7ea71a1116/xlsxwriter.class.php#L266

I have the following code using XLSXWriter, in a project which I'm trying to migrate to use openspout instead (and this is the last sticking point) .. 

```
if ($lines > 1) { $row_options['height'] = $lines * 12.1; }
$writer->writeSheetRow('Sheet1', array_values($row), $row_options);
```

The idea is to give a row with a multi-line cell in it the height of those multiple lines. Works as expected in XLSXWriter with the above code.

I'm very happy to make this PR (as I did for wrapText and cellVerticalAlignment), but I am currently stuck on this one :(

**Comment by Slamdunk** [comment]
> The idea is to give a row with a multi-line cell in it the height of those multiple lines.

This sounds a step forward.
Start with implementing the basic functionality of setting the row height: you can create a PR with solely the test, and then proceed to get it pass in further commits to push later.
