### ISSUE TITLE
Unable to add options to ReaderFactory::createFromFile

### ISSUE THREAD

**Issue by cmple** [openspout/openspout#72]
Hi,
it looks like it is currently impossible to add options to the `createFromFile` function:

```php
$options = new Options();
$options->SHOULD_PRESERVE_EMPTY_ROWS = true;
$reader = ReaderFactory::createFromFile($importPath);
$reader->open($importPath);
```

Is there another way of achieving this?

Thanks!

**Comment by Slamdunk** [comment]
Hi, I kept `ReaderFactory::createFromFile` API just for the guessing capabilities but I strongly discourage its usage and will deprecate it in the next major.

You should already know which type of file you are going to parse (CSV, ODS or XLSX) and then instantiate the class accordingly:

```php
$options = new \OpenSpout\Reader\CSV\Options();
$options->SHOULD_PRESERVE_EMPTY_ROWS = true;
$reader = new \OpenSpout\Reader\CSV\Reader($options);
$reader->open($importPath);
```
