### ISSUE TITLE
Question on usage on project

### ISSUE THREAD

**Issue by niksxs** [openspout/openspout#79]
Hello,

i have used Spout 3.3 for a while without composer. Now i have problems with Spout and wanted to switch to OpenSpout.
I installed composer, installed openspout and now I want to use it in my project. 

My Code looks like the following:
`use OpenSpout\Writer\Common\Creator\WriterEntityFactory;`
`use OpenSpout\Writer\XLSX\Writer;`
`use OpenSpout\Common\Entity\Cell;`
`use OpenSpout\Common\Entity\Row;`

`writer = new \OpenSpout\Writer\XLSX\Writer();`

I always get the following error:
Fatal error: Uncaught Error: Class "OpenSpout\Writer\XLSX\Writer" not found in

Can you help me to switch to openspout. Maybe i am doing something wrong. If you need anything feel free to ask.

Thanks folks

**Comment by mikeleeman** [comment]
Hi, how did you solve it? I also installed via composer, but having the same issue.

Class "OpenSpout\Writer\Common\Creator\WriterEntityFactory" not found

**Comment by niksxs** [comment]
Sry for late answer. You need to be in the correct folder if you use
composer. You need to be in the dir where you want your dependencies

liewyi ***@***.***> schrieb am So., 17. Juli 2022, 20:47:
