### ISSUE TITLE
Question about getCells and getCellAtIndex in 4.x

### ISSUE THREAD

**Issue by mgtremaine** [openspout/openspout#82]
I didn't find an example of the getCells usage in the docs. (maybe I missed it).

I see the it is returning an object inside the getRowIterator but how to you just read the value of a specific cell index.

Something as simple as ....

```php
$col = 1;
foreach ($sheet->getRowIterator() as $row) {
   $cells = $row->getCells();
    echo $cells[$col] . "\n";
}
```

**Comment by mgtremaine** [comment]
I guess I figured it out.

```php
$col = 1;
foreach ($sheet->getRowIterator() as $row) {
   $cells = $row->getCells();
   $cell_value = $cells[$col]->getValue();
    echo cell_value . "\n";
}
```

In box/spout I was able to get the value directly which is why I was asking.. It might be of value to put the getValue() example in one of the guides. Feel free to close this.

**Comment by Slamdunk** [comment]
Hi, would you be so kind to send a PR to improve the doc?

**Comment by mgtremaine** [comment]
PR created...
