### ISSUE TITLE
styles.xml and workbook.xml are added twice to the archive on Windows

### ISSUE THREAD

**Issue by sutrik** [openspout/openspout#85]
Using PHP 8.1.5 and OpenSpout 4.6.2 on Windows 10.

addFileToArchiveWithCompressionMethod() adds "xl\workbook.xml" and "xl\styles.xml"
then addFolderToArchive() re-adds them as "xl/workbook.xml" and "xl/styles.xml"
Notice the different directory separators.

$zip->locateName() in shouldSkipFile() fails to see them as duplicates and they are not overwritten either. The files end up in the zip archive twice. The end result is that at least Excel 2010 says that the file is corrupt (but is able to repair it). And of course the file is bigger than it should be.

I upgraded to OpenSpout from an older Spout 2.x, where this issue didn't exist. So then I noticed that if I revert this change in the FileSystemHelper.php, everything works fine again:

```
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME.\DIRECTORY_SEPARATOR.self::WORKBOOK_XML_FILE_NAME);
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME.\DIRECTORY_SEPARATOR.self::STYLES_XML_FILE_NAME);
```
=>

```
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME . '/' . self::WORKBOOK_XML_FILE_NAME);
$this->zipHelper->addFileToArchive($zip, $this->rootFolder, self::XL_FOLDER_NAME . '/' . self::STYLES_XML_FILE_NAME);
```

**Comment by Slamdunk** [comment]
Hi, nice catch. Can you propose a tested fix within a PR please?
