### ISSUE TITLE
[Question] Box\Spout\Writer\Common\Creator\Style\StyleBuilder alternative 

### ISSUE THREAD

**Issue by JF-626164** [openspout/openspout#94]
Hello! I am working on integrating openspout into my project and I was previously using Box\Spout. 

I am currently using Box\Spout\Writer\Common\Creator\Style\StyleBuilder to create excel sheets for download. Is there an alternative for this in Open Spout?  I tried swapping the Box\Spout with OpenSpout but its giving me an unknown type error: Undefined type 'OpenSpout\Writer\Common\Creator\Style\StyleBuilder'.

**Comment by Slamdunk** [comment]
`StyleBuilder` added no value over the underlying `Style` class. Just use the latter.
